experiment:
  logger:
    log_level: 'INFO'
    custom_file_handler_path: False
    file_handler_path: ''
  running:
    seed: 0
    max_episode: 100
    max_timestep: 100
    save_cycle: 800
    target_model_update_cycle: 500
    buffer_size: 128
    batch_size: 32

model:
  input_dim: None
  output_dim: None
  hidden_l1_dim: 64
  hidden_l2_dim: 128
  optimizer: 'rmsprop' #adam
  loss: 'mse'
  algo: 'qmix' # 'vdn', 'iql'
  alpha: 0.001 # lr for optimizer
  gamma: 0.8 # lr for future reward
  phi: 0.5 # factor for balance g_values
  guide: True # whether to use guide
  beta: 2 # factor control long-term risk

env:
  env_name: 'mpe' # 'smac'
  map_name: 'reference'
  seed: 0
  communicate: True
  msg_len: 10
