experiment:
  logger:
    log_level: 'INFO'
    custom_file_handler_path: False
    file_handler_path: ''
  running:
    seed: 0
    max_episode: 100
    max_timestep: 100

model:
  input_dim: None
  output_dim: None
  hidden_l1_dim: 64
  hidden_l2_dim: 128
  optimizer: 'rmsprop'
  loss: 'mse'
  algo: 'qmix' # 'vdn', 'iql'

env:
  env_name: 'mpe' # 'smac'
  map_name: 'reference'
  seed: 0
  communicate: True
  msg_len: 10
