experiment:
  logger:
    log_level: 'INFO'
    custom_file_handler_path: False
    file_handler_path: ''
  running:
    seed: 1122
    episode: 5
    timestep: 1000  # max_timestep, goto env param to set specific length
    buffer_size: 128
    batch_size: 32
    epoch: 1
    mode: 'exp' # ['exp', 'tune', 'debug']
    save_pdf: False
    batches: ['c-qmix', 'gmix', 'qmix', 'c-gmix'] # ['qmix', 'c-qmix', 'gmix', 'c-gmix', 'vdn', 'iql']

model:
  hidden_l1_dim: 64
  hidden_l2_dim: 128
  optimizer: 'rmsprop' #adam
  loss: 'mse'
  save_cycle: 500
  target_model_update_cycle: 500
  algo: 'qmix' # ['qmix', 'c-qmix', 'gmix', 'c-gmix', 'vdn', 'iql']
  alpha: 0.001 # lr for optimizer
  gamma: 0.8 # lr for future reward
  share: True # agents ues the same NN, switch to expand obs_space (add one hot(agent_num))
  # safe
  guide: True # whether to use guide
  phi: 0.5 # factor for balance g_values in qvalue fixing
  beta: 2 # factor control long-term risk
  # comm
  comm: True # whether to use comm
  sigma: 3 # communication range
  share_param: False


env:
  param: 'preset' # 'test', 'finetuned'
  env_name: 'mpe' # 'smac'
  map_name: 'reference'
  seed: 0
  communicate: True
  msg_len: 10

plot:
  cmap: 'Set2'
  fontsize: 15
  font_family: 'Times New Roman'
  theme: 'seaborn'
  save_recent_n_episode: 10
  keep_live: True
